name: Set Global Variables

outputs:
  EmailRecipients:
    description: 'Email Recipients'
    value: ${{ steps.globals.outputs.EmailRecipients }}
  CICDKey:
    description: 'CICD Key'
    value: ${{ steps.globals.outputs.CICDKey }}

runs:
  using: "composite"

  steps:

    - name: Debug Directory
      run: ls -al ${{ github.action_path }}
      shell: bash

    - name: Set Global Variables
      shell: bash
      id: globals
      run: ${{ github.action_path }}/globals.sh
      # Rus a script global.sh to set the global variables