name: Build & Deploy Angular App

on:
    push:
        branches: [main]

jobs:
    build-angular:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'

            - name: Install Dependencies
              run: |
               cd angular-app
               npm install

            - name: Build Angular App
              run: |
                cd angular-app
                npm run build
            
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifact
                  path: angular-app/dist

    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Test job
              run: echo "test-job"

    deploy-angular:
        runs-on: ubuntu-latest
       # needs: build-angular // For a one job.
        # needs: // List of dependencies can be displayed like this as well
        #     - build-angular
        #     - test-job
        if: ${{ always() }} # No matter whether dependent jobs are successful or failed after finishing them this job will start
        needs: [build-angular, test-job]

        steps:
            - name: Test
              run: echo "Test step"

    deploy-angular-2:
        runs-on: ubuntu-latest
        needs: build-angular

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: build-artifact
                  path: artifact

            - name: Display structure of downloaded artifact
              run: ls -R artifact
