name: Composite Action

on:
  push:
    branches: [main]

jobs:
  composition-action:
    runs-on: ubuntu-latest

    # steps:
    #   - name: Check composite Action
    #     uses: manojtharindu11/composite-github-actions@main

    steps:
      - uses: actions/checkout@v4 # Make sure to add this line access the environment file within the same repository.
    
      - name: Check composite Action
        id: setup-build-env # Can give any name
        # uses: manojtharindu11//set-up-build-environment-github-actions@v4 # Access other repository
        uses: ./actions/setup-build-environment
        with:
          pythonVersion: 3.10
          NodeJSVersion: 18.20.4
          
      - name: Output from action
        run: | 
          echo "Repository Owner = ${{ steps.setup-build-env.outputs.repoOwner }}"
          echo "Default Branch = ${{ steps.setup-build-env.outputs.DefaultBranch }}"
          echo "CICD Key = ${{ steps.setup-build-env.outputs.CICDKey }}"


