name: Concurrency Control

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false # If this is true, the currently running job will be canceled and the new job will be started.

jobs:
    Sleep:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 10 seconds
              run: sleep 10 
