name: Concurrency Control

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    Sleep:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 10 seconds
              run: sleep 10
