name: Deploy Angular App

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy-angular:
        runs-on: ubuntu-latest

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: build-artifact
                  path: artifact
                  github-token: ${{ github.token }}
                  repository: ${{ github.repository }} # manojtharindu11/repository-name
                  run-id: 12610682509 # This is the run id of the build-angular job. but it wouldn't worked for me.

            - name: Display structure of downloaded artifact
              run: ls -R artifact
