name: Manual Workflow

on:
    workflow_dispatch:
        # can add the input as well
        inputs:
            name:
                description: 'Name'
                type: string
                required: true
                default: 'test'
            age:
                description: 'Age'
                type: number
                required: true    
            


jobs:
    manual:
        runs-on: ubuntu-latest

        steps:
            - name: Greeting
              run: echo "Hello, ${{inputs.name}}"

            - name: Age
              run: echo "Your age is ${{inputs.age}}"
