name: Manual Workflow

on:
    workflow_dispatch:
        # can add the input as well
        inputs:
            name:
                description: 'Name'
                type: string
                required: true
                default: 'test'
            age:
                description: 'Age'
                type: number
                required: true    
            gender:
                description: 'Gender'
                type: choice
                options:
                    - Male
                    - Female
                    - Other
            married:
                description: 'Is married'
                type: boolean

jobs:
    manual:
        runs-on: ubuntu-latest

        steps:
            - name: Greeting
              run: echo "Hello, ${{inputs.name}}"

            - name: Age
              run: echo "Your age is ${{inputs.age}}"

            - name: Gender
              run: echo "${{inputs.gender}}"

            - name: Married
              run: echo "Married ${{inputs.married}}"
