name: Manual Workflow

on:
    workflow_dispatch:
        # can add the input as well
        inputs:
            name:
                description: 'Name'
                type: string
                required: true
                default: 'test'


jobs:
    manual:
        runs-on: ubuntu-latest

        steps:
            - name: Greeting
              run: echo "Hello, world!"