name: Scheduled Workflow
on:
    workflow_dispatch:
    schedule:
        - cron: '*/5 * * * *'

jobs:
    demo:
        runs-on: ubuntu-latest

        steps:
            - name: Log times
              run: |
                current_date_time=${date}
                echo "Current date and time: $current_date_time"