name: Step Output

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: set output
      id: set-output
      shell: bash # Do need to specify, Default is bash
      run: | 
        echo "age=23" >> $GITHUB_OUTPUT
        echo "name=Tharindu Manoj" >> $GITHUB_OUTPUT

    - name: access output
      run: |
        echo "The name of the output name is : ${{ steps.set-output.outputs.name }}"
        echo "the age of the output age is : ${{ steps.set-output.outputs.age }}"

      
